name: PlayerCheck
version: 1.0.1
author: FendiTony
description: Very simple plugin to check if a player is using hacks this plugin adverts him and freeze him!
website: https://fenditony.github.io/
main: me.bukkit.vipera37.PlayerCheck
commands:
check:
usage: /check <player> 
