name: PlayerCheck
main: me.bukkit.vipera37.PlayerCheck
version: 1.0
commands:
   check:
      description: dank aaaa sdadsd
      usage: /<command>
   uncheck:
      description: UNCHECK A PLAYER!
      usage: /<command>
   cinfo: 
      description: informations
      usage: /<command>
